// 赤ちゃんに話しかけたい英語フレーズ・単語集
// en: 英語 / ja: 日本語訳 / emoji: アイコン / tag: カテゴリ
const WORDS = [
  { en: "Good morning!", ja: "おはよう!", emoji: "☀️", tag: "あいさつ" },
  { en: "Good night.", ja: "おやすみ。", emoji: "🌙", tag: "あいさつ" },
  { en: "I love you.", ja: "だいすきだよ。", emoji: "💕", tag: "きもち" },
  { en: "Hello!", ja: "こんにちは!", emoji: "👋", tag: "あいさつ" },
  { en: "Peek-a-boo!", ja: "いないいないばあ!", emoji: "🙈", tag: "あそび" },
  { en: "Let's eat.", ja: "たべようね。", emoji: "🍽️", tag: "せいかつ" },
  { en: "Yummy!", ja: "おいしいね!", emoji: "😋", tag: "せいかつ" },
  { en: "Here's your milk.", ja: "ミルクだよ。", emoji: "🍼", tag: "たべもの" },
  { en: "Here's some water.", ja: "おみずだよ。", emoji: "💧", tag: "たべもの" },
  { en: "Look, a ball!", ja: "ボールだよ!", emoji: "⚽", tag: "おもちゃ" },
  { en: "Look, a dog!", ja: "わんわんだよ!", emoji: "🐶", tag: "どうぶつ" },
  { en: "Look, a cat!", ja: "にゃんにゃんだよ!", emoji: "🐱", tag: "どうぶつ" },
  { en: "Look, a bird!", ja: "とりさんだよ!", emoji: "🐦", tag: "どうぶつ" },
  { en: "Look, a fish!", ja: "おさかなだよ!", emoji: "🐟", tag: "どうぶつ" },
  { en: "Look, a bear!", ja: "くまさんだよ!", emoji: "🐻", tag: "どうぶつ" },
  { en: "Look, a bunny!", ja: "うさぎさんだよ!", emoji: "🐰", tag: "どうぶつ" },
  { en: "Time for a bath.", ja: "おふろの時間だよ。", emoji: "🛁", tag: "せいかつ" },
  { en: "So warm.", ja: "あったかいね。", emoji: "♨️", tag: "きもち" },
  { en: "Clean and fresh!", ja: "さっぱりしたね!", emoji: "🧼", tag: "せいかつ" },
  { en: "Let's sleep.", ja: "ねんねしようね。", emoji: "😴", tag: "せいかつ" },
  { en: "Sweet dreams.", ja: "いいゆめをみてね。", emoji: "💤", tag: "きもち" },
  { en: "Are you sleepy?", ja: "ねむいのかな?", emoji: "🥱", tag: "きもち" },
  { en: "Are you hungry?", ja: "おなかすいたかな?", emoji: "🍚", tag: "きもち" },
  { en: "Well done!", ja: "よくできたね!", emoji: "🎉", tag: "はげまし" },
  { en: "You can do it!", ja: "できるよ!", emoji: "💪", tag: "はげまし" },
  { en: "Good job!", ja: "じょうずだね!", emoji: "👏", tag: "はげまし" },
  { en: "Let's go outside.", ja: "おそとに行こうね。", emoji: "🌳", tag: "せいかつ" },
  { en: "What a nice day!", ja: "いいお天気だね!", emoji: "🌤️", tag: "せいかつ" },
  { en: "It's raining.", ja: "あめがふっているね。", emoji: "🌧️", tag: "せいかつ" },
  { en: "Look, the sun!", ja: "たいようだよ!", emoji: "☀️", tag: "しぜん" },
  { en: "Look, the moon!", ja: "おつきさまだよ!", emoji: "🌕", tag: "しぜん" },
  { en: "Look, a star!", ja: "おほしさまだよ!", emoji: "⭐", tag: "しぜん" },
  { en: "Look, a flower!", ja: "おはなだよ!", emoji: "🌸", tag: "しぜん" },
  { en: "Look, a tree!", ja: "きだよ!", emoji: "🌳", tag: "しぜん" },
  { en: "This is a book.", ja: "ほんだよ。", emoji: "📖", tag: "おもちゃ" },
  { en: "Let's read a book.", ja: "ほんをよもうね。", emoji: "📚", tag: "あそび" },
  { en: "Shall we sing?", ja: "うたおうか?", emoji: "🎵", tag: "あそび" },
  { en: "Let's dance!", ja: "おどろうね!", emoji: "💃", tag: "あそび" },
  { en: "Let's play!", ja: "あそぼうね!", emoji: "🧸", tag: "あそび" },
  { en: "That's funny!", ja: "おもしろいね!", emoji: "😂", tag: "きもち" },
  { en: "Are you happy?", ja: "うれしいのかな?", emoji: "😊", tag: "きもち" },
  { en: "It's okay.", ja: "だいじょうぶだよ。", emoji: "🤗", tag: "きもち" },
  { en: "I'm here.", ja: "ここにいるよ。", emoji: "🫂", tag: "きもち" },
  { en: "I'm your mama.", ja: "ママだよ。", emoji: "👩", tag: "かぞく" },
  { en: "I'm your dada.", ja: "パパだよ。", emoji: "👨", tag: "かぞく" },
  { en: "We're a family.", ja: "かぞくだね。", emoji: "👨‍👩‍👧", tag: "かぞく" },
  { en: "You're my baby.", ja: "あなたはあかちゃんだよ。", emoji: "👶", tag: "かぞく" },
  { en: "This is your hand.", ja: "これは てだよ。", emoji: "✋", tag: "からだ" },
  { en: "This is your foot.", ja: "これは あしだよ。", emoji: "🦶", tag: "からだ" },
  { en: "These are your eyes.", ja: "これは めだよ。", emoji: "👀", tag: "からだ" },
  { en: "This is your nose.", ja: "これは はなだよ。", emoji: "👃", tag: "からだ" },
  { en: "These are your ears.", ja: "これは みみだよ。", emoji: "👂", tag: "からだ" },
  { en: "This is your head.", ja: "これは あたまだよ。", emoji: "🧠", tag: "からだ" },
  { en: "This is your tummy.", ja: "これは おなかだよ。", emoji: "🫃", tag: "からだ" },
  { en: "This is so big!", ja: "おおきいね!", emoji: "🐘", tag: "ようす" },
  { en: "This is so small!", ja: "ちいさいね!", emoji: "🐁", tag: "ようす" },
  { en: "This is hot!", ja: "あついね!", emoji: "🔥", tag: "ようす" },
  { en: "This is cold!", ja: "つめたいね!", emoji: "❄️", tag: "ようす" },
  { en: "This is so soft.", ja: "やわらかいね。", emoji: "🧸", tag: "ようす" },
  { en: "Up we go!", ja: "たかいたかい!", emoji: "🙆", tag: "あそび" },
  { en: "Round and round.", ja: "ぐるぐる。", emoji: "🌀", tag: "あそび" },
  { en: "Clap your hands.", ja: "ぱちぱちしようね。", emoji: "👏", tag: "あそび" },
  { en: "One, two, three!", ja: "いち、に、さん!", emoji: "🔢", tag: "かず" },
  { en: "This is red.", ja: "あかだね。", emoji: "🔴", tag: "いろ" },
  { en: "This is blue.", ja: "あおだね。", emoji: "🔵", tag: "いろ" },
  { en: "This is yellow.", ja: "きいろだね。", emoji: "🟡", tag: "いろ" },
  { en: "This is green.", ja: "みどりだね。", emoji: "🟢", tag: "いろ" },
  { en: "Let's brush your teeth.", ja: "はをみがこうね。", emoji: "🪥", tag: "せいかつ" },
  { en: "Let's get dressed.", ja: "おきがえしようね。", emoji: "👕", tag: "せいかつ" },
  { en: "Shoes on!", ja: "くつをはこうね!", emoji: "👟", tag: "せいかつ" },
  { en: "Let's go for a walk.", ja: "おさんぽに行こうね。", emoji: "🚶", tag: "せいかつ" },
  { en: "Look, a car!", ja: "くるまだよ!", emoji: "🚗", tag: "のりもの" },
  { en: "Look, a train!", ja: "でんしゃだよ!", emoji: "🚃", tag: "のりもの" },
  { en: "Look, an airplane!", ja: "ひこうきだよ!", emoji: "✈️", tag: "のりもの" },
  { en: "It's so cute.", ja: "かわいいね。", emoji: "🥰", tag: "きもち" },
  { en: "You're amazing.", ja: "すごいね。", emoji: "🌟", tag: "はげまし" },
  { en: "Thank you.", ja: "ありがとう。", emoji: "🙏", tag: "あいさつ" },
  { en: "See you later.", ja: "またあとでね。", emoji: "👋", tag: "あいさつ" },
  { en: "Welcome home.", ja: "おかえり。", emoji: "🏠", tag: "あいさつ" },
  { en: "I'm home.", ja: "ただいま。", emoji: "🚪", tag: "あいさつ" },
  { en: "It's nap time.", ja: "おひるねの時間だよ。", emoji: "🛏️", tag: "せいかつ" },
  { en: "Don't cry.", ja: "なかないでね。", emoji: "🥲", tag: "きもち" },
  { en: "It's all right, take your time.", ja: "ゆっくりでいいよ。", emoji: "🐢", tag: "はげまし" },
  { en: "Let's try again.", ja: "もういちどやってみようね。", emoji: "🔁", tag: "はげまし" },
  { en: "High five!", ja: "ハイタッチ!", emoji: "🙌", tag: "あそび" },
  { en: "Look, a bubble!", ja: "しゃぼんだまだよ!", emoji: "🫧", tag: "あそび" },
  { en: "Splash!", ja: "ばしゃばしゃ!", emoji: "💦", tag: "あそび" },
  { en: "Yay!", ja: "やったー!", emoji: "🙆‍♀️", tag: "きもち" },
  { en: "Look, it's snowing!", ja: "ゆきだよ!", emoji: "❄️", tag: "しぜん" },
  { en: "Feel the wind.", ja: "かぜだね。", emoji: "🌬️", tag: "しぜん" },
  { en: "Look, a cloud!", ja: "くもだよ!", emoji: "☁️", tag: "しぜん" },
  { en: "Look, a rainbow!", ja: "にじだよ!", emoji: "🌈", tag: "しぜん" },

  // ---- あいさつ ----
  { en: "Good afternoon!", ja: "いい午後だね!", emoji: "🌤️", tag: "あいさつ" },
  { en: "Excuse me.", ja: "しつれいします。", emoji: "🙇", tag: "あいさつ" },
  { en: "I'm sorry.", ja: "ごめんね。", emoji: "🥺", tag: "あいさつ" },
  { en: "Please.", ja: "おねがい。", emoji: "🙏", tag: "あいさつ" },
  { en: "You're welcome.", ja: "どういたしまして。", emoji: "😊", tag: "あいさつ" },
  { en: "Nice to meet you.", ja: "はじめまして。", emoji: "🤝", tag: "あいさつ" },
  { en: "See you tomorrow.", ja: "またあしたね。", emoji: "🌙", tag: "あいさつ" },
  { en: "Happy birthday!", ja: "たんじょうびおめでとう!", emoji: "🎂", tag: "あいさつ" },

  // ---- きもち ----
  { en: "Are you excited?", ja: "わくわくするね?", emoji: "🤩", tag: "きもち" },
  { en: "Were you surprised?", ja: "びっくりしたね?", emoji: "😲", tag: "きもち" },
  { en: "I'm so proud of you.", ja: "とてもほこらしいよ。", emoji: "🥹", tag: "きもち" },
  { en: "Are you shy?", ja: "はずかしいのかな?", emoji: "😳", tag: "きもち" },
  { en: "It's okay to be scared.", ja: "こわくてもだいじょうぶだよ。", emoji: "😨", tag: "きもち" },
  { en: "Are you thirsty?", ja: "のどがかわいたかな?", emoji: "🥤", tag: "きもち" },
  { en: "Are you bored?", ja: "ひまなのかな?", emoji: "😑", tag: "きもち" },
  { en: "You're so curious.", ja: "きょうみしんしんだね。", emoji: "🧐", tag: "きもち" },
  { en: "That tickles!", ja: "くすぐったいね!", emoji: "🤭", tag: "きもち" },
  { en: "Are you comfy?", ja: "きもちいいかな?", emoji: "😌", tag: "きもち" },
  { en: "It's a bit uncomfortable.", ja: "ちょっときもちわるいね。", emoji: "😖", tag: "きもち" },
  { en: "Are you in pain?", ja: "いたいのかな?", emoji: "🤕", tag: "きもち" },
  { en: "You're so brave.", ja: "ゆうきがあるね。", emoji: "🦁", tag: "きもち" },
  { en: "Silly you!", ja: "おちゃめだね!", emoji: "🤪", tag: "きもち" },
  { en: "Are you grumpy?", ja: "きげんななめかな?", emoji: "😤", tag: "きもち" },
  { en: "I missed you.", ja: "さみしかったよ。", emoji: "🥺", tag: "きもち" },
  { en: "You feel safe here.", ja: "ここはあんしんだよ。", emoji: "🛡️", tag: "きもち" },
  { en: "You're calm now.", ja: "おちついたね。", emoji: "🧘", tag: "きもち" },

  // ---- あそび ----
  { en: "Let's play hide and seek.", ja: "かくれんぼしようね。", emoji: "🙈", tag: "あそび" },
  { en: "Let's play tag.", ja: "おにごっこしようね。", emoji: "🏃", tag: "あそび" },
  { en: "Let's build with blocks.", ja: "つみきであそぼうね。", emoji: "🧱", tag: "あそび" },
  { en: "Let's draw a picture.", ja: "おえかきしようね。", emoji: "🖍️", tag: "あそび" },
  { en: "Let's color together.", ja: "いろをぬろうね。", emoji: "🎨", tag: "あそび" },
  { en: "Let's jump!", ja: "ジャンプしようね!", emoji: "🤸", tag: "あそび" },
  { en: "Let's run!", ja: "はしろうね!", emoji: "🏃‍♀️", tag: "あそび" },
  { en: "Let's climb up.", ja: "のぼろうね。", emoji: "🧗", tag: "あそび" },
  { en: "Let's swim!", ja: "およごうね!", emoji: "🏊", tag: "あそび" },
  { en: "Let's play catch.", ja: "キャッチボールしようね。", emoji: "⚾", tag: "あそび" },
  { en: "Tickle tickle!", ja: "こちょこちょ!", emoji: "🤗", tag: "あそび" },
  { en: "Piggyback ride!", ja: "おんぶしようね!", emoji: "🐴", tag: "あそび" },
  { en: "Let's swing.", ja: "ブランコにのろうね。", emoji: "🛝", tag: "あそび" },
  { en: "Let's go down the slide.", ja: "すべりだいをすべろうね。", emoji: "🛝", tag: "あそび" },
  { en: "Let's fly a kite.", ja: "たこあげしようね。", emoji: "🪁", tag: "あそび" },
  { en: "Let's play with puzzles.", ja: "パズルであそぼうね。", emoji: "🧩", tag: "あそび" },
  { en: "Let's stack the cups.", ja: "コップをかさねようね。", emoji: "🥤", tag: "あそび" },
  { en: "Let's play peekaboo again.", ja: "またいないいないばあしようね。", emoji: "🙈", tag: "あそび" },
  { en: "Let's dance to music.", ja: "おんがくにあわせておどろうね。", emoji: "🎶", tag: "あそび" },

  // ---- せいかつ ----
  { en: "Let's wash your hands.", ja: "てをあらおうね。", emoji: "🧼", tag: "せいかつ" },
  { en: "Let's brush your hair.", ja: "かみをとかそうね。", emoji: "💇", tag: "せいかつ" },
  { en: "Time for a diaper change.", ja: "おむつをかえようね。", emoji: "👶", tag: "せいかつ" },
  { en: "Let's put on your socks.", ja: "くつしたをはこうね。", emoji: "🧦", tag: "せいかつ" },
  { en: "Let's tie your shoes.", ja: "くつひもをむすぼうね。", emoji: "👟", tag: "せいかつ" },
  { en: "Let's pack your bag.", ja: "かばんにつめようね。", emoji: "🎒", tag: "せいかつ" },
  { en: "Time for daycare.", ja: "ほいくえんの時間だよ。", emoji: "🏫", tag: "せいかつ" },
  { en: "Welcome back from daycare!", ja: "ほいくえん、おかえり!", emoji: "🏫", tag: "せいかつ" },
  { en: "Let's watch a little TV.", ja: "テレビをみようね。", emoji: "📺", tag: "せいかつ" },
  { en: "One more book before bed.", ja: "ねるまえにもう1さつよもうね。", emoji: "📖", tag: "せいかつ" },
  { en: "Let's turn off the light.", ja: "でんきをけそうね。", emoji: "💡", tag: "せいかつ" },
  { en: "Let's clean up the toys.", ja: "おもちゃをかたづけようね。", emoji: "🧸", tag: "せいかつ" },
  { en: "Time for breakfast.", ja: "あさごはんの時間だよ。", emoji: "🍳", tag: "せいかつ" },
  { en: "Time for lunch.", ja: "おひるごはんの時間だよ。", emoji: "🍱", tag: "せいかつ" },
  { en: "Time for dinner.", ja: "ばんごはんの時間だよ。", emoji: "🍚", tag: "せいかつ" },
  { en: "Let's drink some juice.", ja: "ジュースをのもうね。", emoji: "🧃", tag: "せいかつ" },
  { en: "Bottle time.", ja: "ほにゅうびんの時間だよ。", emoji: "🍼", tag: "せいかつ" },
  { en: "Bless you!", ja: "おだいじに。", emoji: "🤧", tag: "せいかつ" },
  { en: "Did you hiccup?", ja: "しゃっくりでたね。", emoji: "😳", tag: "せいかつ" },
  { en: "Let's burp you.", ja: "げっぷさせようね。", emoji: "🍼", tag: "せいかつ" },
  { en: "Let's brush your teeth again.", ja: "はをもういちどみがこうね。", emoji: "🪥", tag: "せいかつ" },
  { en: "Let's trim your nails.", ja: "つめをきろうね。", emoji: "💅", tag: "せいかつ" },
  { en: "Let's clean your ears.", ja: "みみをきれいにしようね。", emoji: "👂", tag: "せいかつ" },
  { en: "Let's check your temperature.", ja: "たいおんをはかろうね。", emoji: "🌡️", tag: "せいかつ" },
  { en: "Time to see the doctor.", ja: "びょういんにいこうね。", emoji: "🩺", tag: "せいかつ" },
  { en: "That's a good vaccination.", ja: "よくがんばったね、ちゅうしゃ。", emoji: "💉", tag: "せいかつ" },
  { en: "Let's use the potty.", ja: "トイレにいってみようね。", emoji: "🚽", tag: "せいかつ" },
  { en: "You slept so well.", ja: "よくねむれたね。", emoji: "😴", tag: "せいかつ" },
  { en: "Good morning, did you sleep well?", ja: "おはよう、よくねむれた?", emoji: "☀️", tag: "せいかつ" },
  { en: "Let's stretch.", ja: "のびをしようね。", emoji: "🙆", tag: "せいかつ" },
  { en: "Are you yawning?", ja: "あくびしてるね。", emoji: "🥱", tag: "せいかつ" },
  { en: "Let's wake up slowly.", ja: "ゆっくりおきようね。", emoji: "🌅", tag: "せいかつ" },
  { en: "Time to get up!", ja: "おきる時間だよ!", emoji: "⏰", tag: "せいかつ" },
  { en: "Let's fold the laundry.", ja: "せんたくものをたたもうね。", emoji: "👕", tag: "せいかつ" },
  { en: "Let's hang the laundry.", ja: "せんたくものをほそうね。", emoji: "🧺", tag: "せいかつ" },
  { en: "Let's set the table.", ja: "テーブルをじゅんびしようね。", emoji: "🍽️", tag: "せいかつ" },
  { en: "Let's wipe your mouth.", ja: "おくちをふこうね。", emoji: "🧻", tag: "せいかつ" },
  { en: "Let's put on your hat.", ja: "ぼうしをかぶろうね。", emoji: "🧢", tag: "せいかつ" },
  { en: "Let's put on your coat.", ja: "コートをきようね。", emoji: "🧥", tag: "せいかつ" },
  { en: "It's chilly, let's bundle up.", ja: "さむいからあったかくしようね。", emoji: "🧣", tag: "せいかつ" },
  { en: "Let's open the window.", ja: "まどをあけようね。", emoji: "🪟", tag: "せいかつ" },
  { en: "Let's water the plants.", ja: "おみずをあげようね。", emoji: "🪴", tag: "せいかつ" },
  { en: "Let's feed the pet.", ja: "ペットにごはんをあげようね。", emoji: "🐾", tag: "せいかつ" },
  { en: "Let's sweep the floor.", ja: "ゆかをはこうね。", emoji: "🧹", tag: "せいかつ" },
  { en: "Let's take out the trash.", ja: "ゴミをすてようね。", emoji: "🗑️", tag: "せいかつ" },
  { en: "Let's ride in the stroller.", ja: "ベビーカーにのろうね。", emoji: "🚼", tag: "せいかつ" },
  { en: "Let's buckle up.", ja: "シートベルトをしようね。", emoji: "🚗", tag: "せいかつ" },
  { en: "We're going shopping.", ja: "おかいものにいこうね。", emoji: "🛒", tag: "せいかつ" },
  { en: "Let's say hi to grandma.", ja: "おばあちゃんにあいさつしようね。", emoji: "👵", tag: "せいかつ" },

  // ---- どうぶつ ----
  { en: "Look, a horse!", ja: "うまさんだよ!", emoji: "🐴", tag: "どうぶつ" },
  { en: "Look, a pig!", ja: "ぶたさんだよ!", emoji: "🐷", tag: "どうぶつ" },
  { en: "Look, a cow!", ja: "うしさんだよ!", emoji: "🐮", tag: "どうぶつ" },
  { en: "Look, a sheep!", ja: "ひつじさんだよ!", emoji: "🐑", tag: "どうぶつ" },
  { en: "Look, a chick!", ja: "ひよこさんだよ!", emoji: "🐤", tag: "どうぶつ" },
  { en: "Look, a duck!", ja: "あひるさんだよ!", emoji: "🦆", tag: "どうぶつ" },
  { en: "Look, a frog!", ja: "かえるさんだよ!", emoji: "🐸", tag: "どうぶつ" },
  { en: "Look, a turtle!", ja: "かめさんだよ!", emoji: "🐢", tag: "どうぶつ" },
  { en: "Look, a butterfly!", ja: "ちょうちょだよ!", emoji: "🦋", tag: "どうぶつ" },
  { en: "Look, a bee!", ja: "みつばちだよ!", emoji: "🐝", tag: "どうぶつ" },
  { en: "Look, a ladybug!", ja: "てんとうむしだよ!", emoji: "🐞", tag: "どうぶつ" },
  { en: "Look, an elephant!", ja: "ぞうさんだよ!", emoji: "🐘", tag: "どうぶつ" },
  { en: "Look, a lion!", ja: "らいおんさんだよ!", emoji: "🦁", tag: "どうぶつ" },
  { en: "Look, a monkey!", ja: "おさるさんだよ!", emoji: "🐵", tag: "どうぶつ" },
  { en: "Look, a giraffe!", ja: "きりんさんだよ!", emoji: "🦒", tag: "どうぶつ" },
  { en: "Look, a penguin!", ja: "ぺんぎんさんだよ!", emoji: "🐧", tag: "どうぶつ" },
  { en: "Look, an owl!", ja: "ふくろうさんだよ!", emoji: "🦉", tag: "どうぶつ" },
  { en: "Look, a squirrel!", ja: "りすさんだよ!", emoji: "🐿️", tag: "どうぶつ" },
  { en: "Look, a fox!", ja: "きつねさんだよ!", emoji: "🦊", tag: "どうぶつ" },
  { en: "Look, a koala!", ja: "コアラさんだよ!", emoji: "🐨", tag: "どうぶつ" },
  { en: "Look, a panda!", ja: "ぱんださんだよ!", emoji: "🐼", tag: "どうぶつ" },
  { en: "Look, a hedgehog!", ja: "はりねずみさんだよ!", emoji: "🦔", tag: "どうぶつ" },
  { en: "Look, a snail!", ja: "かたつむりだよ!", emoji: "🐌", tag: "どうぶつ" },
  { en: "Look, an octopus!", ja: "たこさんだよ!", emoji: "🐙", tag: "どうぶつ" },

  // ---- たべもの ----
  { en: "Let's have some rice.", ja: "ごはんをたべようね。", emoji: "🍚", tag: "たべもの" },
  { en: "Bread is yummy.", ja: "パンはおいしいね。", emoji: "🍞", tag: "たべもの" },
  { en: "Let's eat an apple.", ja: "りんごをたべようね。", emoji: "🍎", tag: "たべもの" },
  { en: "Let's eat a banana.", ja: "バナナをたべようね。", emoji: "🍌", tag: "たべもの" },
  { en: "Let's eat some grapes.", ja: "ぶどうをたべようね。", emoji: "🍇", tag: "たべもの" },
  { en: "Let's eat an orange.", ja: "みかんをたべようね。", emoji: "🍊", tag: "たべもの" },
  { en: "Let's eat a strawberry.", ja: "いちごをたべようね。", emoji: "🍓", tag: "たべもの" },
  { en: "Let's eat a peach.", ja: "ももをたべようね。", emoji: "🍑", tag: "たべもの" },
  { en: "Let's eat some carrots.", ja: "にんじんをたべようね。", emoji: "🥕", tag: "たべもの" },
  { en: "Let's eat some potatoes.", ja: "じゃがいもをたべようね。", emoji: "🥔", tag: "たべもの" },
  { en: "Let's eat some corn.", ja: "とうもろこしをたべようね。", emoji: "🌽", tag: "たべもの" },
  { en: "Let's eat some broccoli.", ja: "ブロッコリーをたべようね。", emoji: "🥦", tag: "たべもの" },
  { en: "Let's eat some tomatoes.", ja: "トマトをたべようね。", emoji: "🍅", tag: "たべもの" },
  { en: "Let's have some soup.", ja: "スープをのもうね。", emoji: "🍲", tag: "たべもの" },
  { en: "Let's eat some eggs.", ja: "たまごをたべようね。", emoji: "🥚", tag: "たべもの" },
  { en: "Let's eat some cheese.", ja: "チーズをたべようね。", emoji: "🧀", tag: "たべもの" },
  { en: "Let's have some yogurt.", ja: "ヨーグルトをたべようね。", emoji: "🍦", tag: "たべもの" },
  { en: "Let's eat some noodles.", ja: "めんをたべようね。", emoji: "🍜", tag: "たべもの" },
  { en: "Let's eat some fish today.", ja: "きょうはおさかなをたべようね。", emoji: "🐟", tag: "たべもの" },
  { en: "Let's have a cookie.", ja: "クッキーをたべようね。", emoji: "🍪", tag: "たべもの" },
  { en: "Let's have a piece of cake.", ja: "ケーキをたべようね。", emoji: "🍰", tag: "たべもの" },
  { en: "Let's drink some tea.", ja: "おちゃをのもうね。", emoji: "🍵", tag: "たべもの" },
  { en: "Careful, it's hot food.", ja: "あつい、きをつけてね。", emoji: "♨️", tag: "たべもの" },
  { en: "That was delicious!", ja: "おいしかったね!", emoji: "😋", tag: "たべもの" },
  { en: "Let's wash it down with water.", ja: "おみずでながしこもうね。", emoji: "💧", tag: "たべもの" },
  { en: "Say thank you for the food.", ja: "いただきますって言おうね。", emoji: "🙏", tag: "たべもの" },
  { en: "All done eating!", ja: "ごちそうさまでした!", emoji: "🍽️", tag: "たべもの" },
  { en: "Let's have a snack.", ja: "おやつをたべようね。", emoji: "🍪", tag: "たべもの" },

  // ---- しぜん ----
  { en: "Look at the mountain!", ja: "やまだよ!", emoji: "⛰️", tag: "しぜん" },
  { en: "Look, the sea!", ja: "うみだよ!", emoji: "🌊", tag: "しぜん" },
  { en: "Look, a river!", ja: "かわだよ!", emoji: "🏞️", tag: "しぜん" },
  { en: "Look, the forest!", ja: "もりだよ!", emoji: "🌲", tag: "しぜん" },
  { en: "Look, the grass!", ja: "くさだよ!", emoji: "🌿", tag: "しぜん" },
  { en: "Look, a leaf!", ja: "はっぱだよ!", emoji: "🍃", tag: "しぜん" },
  { en: "Look, the sky!", ja: "そらだよ!", emoji: "🌌", tag: "しぜん" },
  { en: "It's a beautiful sunset.", ja: "きれいなゆうやけだね。", emoji: "🌇", tag: "しぜん" },
  { en: "It's a beautiful sunrise.", ja: "きれいなあさひだね。", emoji: "🌄", tag: "しぜん" },
  { en: "The stars are twinkling.", ja: "ほしがきらきらしてるね。", emoji: "✨", tag: "しぜん" },
  { en: "Feel the sand.", ja: "すなをさわってみようね。", emoji: "🏖️", tag: "しぜん" },
  { en: "Watch the waves.", ja: "なみをみようね。", emoji: "🌊", tag: "しぜん" },
  { en: "It's a rainy day.", ja: "あめのひだね。", emoji: "☔", tag: "しぜん" },
  { en: "It's a sunny day.", ja: "はれてるね。", emoji: "🌞", tag: "しぜん" },
  { en: "It's a windy day.", ja: "かぜがつよいね。", emoji: "🌬️", tag: "しぜん" },
  { en: "Look, fallen leaves!", ja: "おちばだよ!", emoji: "🍂", tag: "しぜん" },

  // ---- のりもの ----
  { en: "Look, a bus!", ja: "バスだよ!", emoji: "🚌", tag: "のりもの" },
  { en: "Look, a bicycle!", ja: "じてんしゃだよ!", emoji: "🚲", tag: "のりもの" },
  { en: "Look, a boat!", ja: "ふねだよ!", emoji: "⛵", tag: "のりもの" },
  { en: "Look, a ship!", ja: "おおきいふねだよ!", emoji: "🚢", tag: "のりもの" },
  { en: "Look, a motorcycle!", ja: "バイクだよ!", emoji: "🏍️", tag: "のりもの" },
  { en: "Look, a fire truck!", ja: "しょうぼうしゃだよ!", emoji: "🚒", tag: "のりもの" },
  { en: "Look, an ambulance!", ja: "きゅうきゅうしゃだよ!", emoji: "🚑", tag: "のりもの" },
  { en: "Look, a police car!", ja: "パトカーだよ!", emoji: "🚓", tag: "のりもの" },
  { en: "Look, a helicopter!", ja: "ヘリコプターだよ!", emoji: "🚁", tag: "のりもの" },
  { en: "Look, a truck!", ja: "トラックだよ!", emoji: "🚚", tag: "のりもの" },
  { en: "The airplane is flying!", ja: "ひこうきがとんでいるよ!", emoji: "✈️", tag: "のりもの" },
  { en: "Shall we go for a drive?", ja: "ドライブしようか?", emoji: "🚗", tag: "のりもの" },

  // ---- からだ ----
  { en: "These are your fingers.", ja: "これは ゆびだよ。", emoji: "🖐️", tag: "からだ" },
  { en: "These are your toes.", ja: "これは あしゆびだよ。", emoji: "🦶", tag: "からだ" },
  { en: "This is your belly button.", ja: "これは おへそだよ。", emoji: "🫃", tag: "からだ" },
  { en: "These are your cheeks.", ja: "これは ほっぺだよ。", emoji: "😊", tag: "からだ" },
  { en: "This is your hair.", ja: "これは かみのけだよ。", emoji: "💇", tag: "からだ" },
  { en: "These are your teeth.", ja: "これは はだよ。", emoji: "🦷", tag: "からだ" },
  { en: "This is your elbow.", ja: "これは ひじだよ。", emoji: "💪", tag: "からだ" },
  { en: "This is your knee.", ja: "これは ひざだよ。", emoji: "🦵", tag: "からだ" },
  { en: "This is your shoulder.", ja: "これは かただよ。", emoji: "🤷", tag: "からだ" },
  { en: "This is your back.", ja: "これは せなかだよ。", emoji: "🔙", tag: "からだ" },
  { en: "This is your chin.", ja: "これは あごだよ。", emoji: "🙂", tag: "からだ" },
  { en: "This is your tongue.", ja: "これは しただよ。", emoji: "👅", tag: "からだ" },
  { en: "This is your mouth.", ja: "これは おくちだよ。", emoji: "👄", tag: "からだ" },

  // ---- かぞく ----
  { en: "This is grandma.", ja: "おばあちゃんだよ。", emoji: "👵", tag: "かぞく" },
  { en: "This is grandpa.", ja: "おじいちゃんだよ。", emoji: "👴", tag: "かぞく" },
  { en: "This is your big brother.", ja: "おにいちゃんだよ。", emoji: "👦", tag: "かぞく" },
  { en: "This is your big sister.", ja: "おねえちゃんだよ。", emoji: "👧", tag: "かぞく" },
  { en: "This is your friend.", ja: "おともだちだよ。", emoji: "🧑‍🤝‍🧑", tag: "かぞく" },
  { en: "We love you so much.", ja: "みんなだいすきだよ。", emoji: "💞", tag: "かぞく" },

  // ---- はげまし ----
  { en: "Try your best!", ja: "がんばれ!", emoji: "💪", tag: "はげまし" },
  { en: "Don't give up!", ja: "あきらめないで!", emoji: "🔥", tag: "はげまし" },
  { en: "I'm proud of you!", ja: "ほこらしいよ!", emoji: "🥹", tag: "はげまし" },
  { en: "Believe in yourself.", ja: "じぶんをしんじてね。", emoji: "✨", tag: "はげまし" },
  { en: "You're so strong.", ja: "つよいね。", emoji: "🦾", tag: "はげまし" },
  { en: "We did it together!", ja: "いっしょにできたね!", emoji: "🙌", tag: "はげまし" },
  { en: "Almost there!", ja: "もうすこしだよ!", emoji: "🏁", tag: "はげまし" },
  { en: "One more time!", ja: "もういっかい!", emoji: "🔁", tag: "はげまし" },
  { en: "Nice try!", ja: "おしい、いいちょうせんだったね!", emoji: "👍", tag: "はげまし" },

  // ---- いろ ----
  { en: "This is purple.", ja: "むらさきだね。", emoji: "🟣", tag: "いろ" },
  { en: "This is pink.", ja: "ピンクだね。", emoji: "🩷", tag: "いろ" },
  { en: "This is black.", ja: "くろだね。", emoji: "⚫", tag: "いろ" },
  { en: "This is white.", ja: "しろだね。", emoji: "⚪", tag: "いろ" },
  { en: "This is brown.", ja: "ちゃいろだね。", emoji: "🟤", tag: "いろ" },
  { en: "This is orange.", ja: "オレンジだね。", emoji: "🟠", tag: "いろ" },

  // ---- ようす ----
  { en: "This is fast!", ja: "はやいね!", emoji: "🏎️", tag: "ようす" },
  { en: "This is slow.", ja: "ゆっくりだね。", emoji: "🐢", tag: "ようす" },
  { en: "This is loud!", ja: "おおきいおとだね!", emoji: "🔊", tag: "ようす" },
  { en: "This is quiet.", ja: "しずかだね。", emoji: "🤫", tag: "ようす" },
  { en: "This is wet.", ja: "ぬれてるね。", emoji: "💦", tag: "ようす" },
  { en: "This is dry now.", ja: "かわいたね。", emoji: "🌬️", tag: "ようす" },
  { en: "You're so tall now!", ja: "おおきくなったね!", emoji: "📏", tag: "ようす" },
  { en: "You were so small.", ja: "ちいさかったね。", emoji: "🤏", tag: "ようす" },
  { en: "This is heavy!", ja: "おもいね!", emoji: "🏋️", tag: "ようす" },
  { en: "This is light.", ja: "かるいね。", emoji: "🪶", tag: "ようす" },
  { en: "This is a new toy.", ja: "あたらしいおもちゃだね。", emoji: "✨", tag: "ようす" },
  { en: "This is your old favorite.", ja: "おきにいりだったね。", emoji: "🧸", tag: "ようす" },
  { en: "It's all clean now.", ja: "きれいになったね。", emoji: "✨", tag: "ようす" },
  { en: "Oops, it's dirty.", ja: "よごれちゃったね。", emoji: "🫧", tag: "ようす" },
  { en: "It's full!", ja: "いっぱいだね!", emoji: "🥛", tag: "ようす" },

  // ---- かず ----
  { en: "Let's count to five.", ja: "5までかぞえようね。", emoji: "🖐️", tag: "かず" },
  { en: "Let's count to ten.", ja: "10までかぞえようね。", emoji: "🔟", tag: "かず" },
  { en: "One apple.", ja: "りんごが1つ。", emoji: "🍎", tag: "かず" },
  { en: "Two hands.", ja: "てが2つ。", emoji: "🙌", tag: "かず" },
  { en: "Three balls.", ja: "ボールが3つ。", emoji: "⚽", tag: "かず" },
  { en: "Four wheels.", ja: "タイヤが4つ。", emoji: "🚗", tag: "かず" },
  { en: "Five fingers.", ja: "ゆびが5ほん。", emoji: "✋", tag: "かず" },
  { en: "How many are there?", ja: "いくつあるかな?", emoji: "🔢", tag: "かず" },
  { en: "Zero left!", ja: "ぜんぶなくなったね!", emoji: "0️⃣", tag: "かず" },

  // ---- おもちゃ ----
  { en: "Look, building blocks!", ja: "つみきだよ!", emoji: "🧱", tag: "おもちゃ" },
  { en: "Look, a puzzle!", ja: "パズルだよ!", emoji: "🧩", tag: "おもちゃ" },
  { en: "Look, a doll!", ja: "おにんぎょうだよ!", emoji: "🪆", tag: "おもちゃ" },
  { en: "Look, a teddy bear!", ja: "くまさんのぬいぐるみだよ!", emoji: "🧸", tag: "おもちゃ" },
  { en: "Let's play the drum.", ja: "たいこをたたこうね。", emoji: "🥁", tag: "おもちゃ" },
  { en: "Let's play the xylophone.", ja: "もっきんをならそうね。", emoji: "🎼", tag: "おもちゃ" },
  { en: "Look, a crayon!", ja: "クレヨンだよ!", emoji: "🖍️", tag: "おもちゃ" },
  { en: "Look, a balloon!", ja: "ふうせんだよ!", emoji: "🎈", tag: "おもちゃ" },

  // ---- おと ----
  { en: "Woof woof!", ja: "わんわん!", emoji: "🐶", tag: "おと" },
  { en: "Meow meow!", ja: "にゃーにゃー!", emoji: "🐱", tag: "おと" },
  { en: "Moo moo!", ja: "もーもー!", emoji: "🐮", tag: "おと" },
  { en: "Oink oink!", ja: "ぶーぶー!", emoji: "🐷", tag: "おと" },
  { en: "Baa baa!", ja: "めーめー!", emoji: "🐑", tag: "おと" },
  { en: "Quack quack!", ja: "がーがー!", emoji: "🦆", tag: "おと" },
  { en: "Ribbit ribbit!", ja: "げろげろ!", emoji: "🐸", tag: "おと" },
  { en: "Tweet tweet!", ja: "ちゅんちゅん!", emoji: "🐦", tag: "おと" },
  { en: "Buzz buzz!", ja: "ぶんぶん!", emoji: "🐝", tag: "おと" },
  { en: "Roar!", ja: "がおー!", emoji: "🦁", tag: "おと" },
  { en: "Tick tock, tick tock.", ja: "ちくたく、ちくたく。", emoji: "🕐", tag: "おと" },
  { en: "Honk honk!", ja: "ぷーぷー!", emoji: "🚗", tag: "おと" },
  { en: "Choo choo!", ja: "がたんごとん!", emoji: "🚃", tag: "おと" },
  { en: "Vroom vroom!", ja: "ぶるるん!", emoji: "🚙", tag: "おと" },
  { en: "Drip drop, drip drop.", ja: "ぽたぽた、ぽたぽた。", emoji: "💧", tag: "おと" },
  { en: "Boom!", ja: "どーん!", emoji: "💥", tag: "おと" },
  { en: "Ding dong!", ja: "ぴんぽーん!", emoji: "🔔", tag: "おと" },
  { en: "Clap clap!", ja: "ぱちぱち!", emoji: "👏", tag: "おと" },
  { en: "Knock knock!", ja: "とんとん!", emoji: "🚪", tag: "おと" },
  { en: "Achoo!", ja: "はくしょん!", emoji: "🤧", tag: "おと" },

  // ---- きせつ ----
  { en: "It's spring!", ja: "はるだね!", emoji: "🌸", tag: "きせつ" },
  { en: "It's summer!", ja: "なつだね!", emoji: "☀️", tag: "きせつ" },
  { en: "It's autumn!", ja: "あきだね!", emoji: "🍁", tag: "きせつ" },
  { en: "It's winter!", ja: "ふゆだね!", emoji: "⛄", tag: "きせつ" },
  { en: "Happy New Year!", ja: "あけましておめでとう!", emoji: "🎍", tag: "きせつ" },
  { en: "Merry Christmas!", ja: "メリークリスマス!", emoji: "🎄", tag: "きせつ" },
  { en: "Happy Halloween!", ja: "ハッピーハロウィン!", emoji: "🎃", tag: "きせつ" },
  { en: "Let's see the cherry blossoms.", ja: "さくらをみにいこうね。", emoji: "🌸", tag: "きせつ" },
  { en: "Let's make a snowman.", ja: "ゆきだるまをつくろうね。", emoji: "⛄", tag: "きせつ" },
  { en: "Let's watch the fireworks.", ja: "はなびをみようね。", emoji: "🎆", tag: "きせつ" },
  { en: "Let's find some fall leaves.", ja: "こうようをさがそうね。", emoji: "🍁", tag: "きせつ" },
  { en: "It's a hot summer day.", ja: "あついなつのひだね。", emoji: "🍉", tag: "きせつ" },
  { en: "It's getting cold, winter's here.", ja: "さむくなってきたね、ふゆだね。", emoji: "❄️", tag: "きせつ" },
];
